-- Sales_data
/*
change invoice_date (text) to invoice_date (date)
*/

alter table sales_data
change column invoice_date invoice_date_old text;

alter table sales_data
add column invoice_date date;

UPDATE sales_data 
SET 
    invoice_date = STR_TO_DATE(invoice_date_old, '%d-%m-%Y');

alter table sales_data
drop column invoice_date_old;

alter table customer_data
change column `ï»¿customer_id` customer_id text;

select customer_id
from customer_data;

-- ```````````` Sales Analysis ``````````````````

-- 1. What is the total sales revenue generated by each shopping mall?

SELECT 
    shopping_mall, ROUND(SUM(price), 2) AS revenue
FROM
    sales_data
GROUP BY shopping_mall;


-- 2. Which product categories have the highest sales in terms of revenue and quantity sold?

-- Top 5 Categories with height sales based on Quantity

SELECT 
    category, SUM(quantity) AS quantity
FROM
    sales_data
GROUP BY category
ORDER BY quantity DESC
LIMIT 5;

-- Top 5 Categories with height sales based on Revenue
SELECT 
    category, ROUND(SUM(price), 2) AS revenue
FROM
    sales_data
GROUP BY category
ORDER BY revenue DESC
LIMIT 5;


-- 3. What is the average order value per customer?

SELECT 
    ROUND(SUM(price) / COUNT(price), 2) AS Avg_order_value_per_customer
FROM
    sales_data;


-- 4. Which day of the week has the highest sales revenue?

SELECT 
    DAYNAME(invoice_date) AS Day,
    ROUND(SUM(price), 2) AS revenue
FROM
    sales_data
GROUP BY Day
ORDER BY revenue DESC
LIMIT 3;


-- 5. What are the monthly sales trends over the past year?

with A as
(select *
from sales_data
where year(invoice_date) = 2023)
select monthname(invoice_date) as month, sum(quantity) as quantity, sum(price) as revenue
from A
group by month
order by revenue desc;

/*
Findings:
In previous year i.e, 2023 sales only happend in January, February and March with decreasing trend.
*/


-- `````````````````````` Customer Behavior ````````````````````````

-- 6. What is the distribution of customer age groups, and how does it relate to their purchasing behavior?

/*
let, customer age group be
< 18 - kids
18 - 29 - young adults
30 - 49 - adults
> 49 - seniors 
*/

alter table customer_data
add column age_group varchar(100);

UPDATE customer_data 
SET 
    age_group = CASE
        WHEN age < 18 THEN 'kids'
        WHEN 18 < age AND age < 29 THEN 'young adults'
        WHEN 29 < age AND age < 49 THEN 'adults'
        ELSE 'seniors'
    END;

SELECT 
    age_group, COUNT(*) AS cnt
FROM
    customer_data
GROUP BY age_group
ORDER BY cnt DESC;

-- * most of customers are from > 49 age ( seniors )

with B as
(with A as
(select age_group, category, count(*) as cnt
from sales_data
natural join customer_data
group by category, age_group
)
select *,
rank() over(partition by age_group order by cnt desc) as rank_
from A)
select * from B where rank_ = 1;
;

-- Every age group is spending more on clothing

-- 7. How does the gender distribution of customers influence the sales of different product categories?

SELECT 
    category, gender, COUNT(*)
FROM
    sales_data
        NATURAL JOIN
    customer_data
GROUP BY category , gender
ORDER BY category;

-- by looking at the result of the query it is observed that in every category Female customers are more than Male

-- 8. Which payment methods are most preferred by customers in different age groups?

with B as
(with A as
(select age_group, payment_method, count(*) as cnt
from customer_data
group by age_group, payment_method
)
select *, rank() over(partition by age_group order by cnt desc) as rank_
from A)
select * from B where rank_ = 1;

-- after observing the query results it is observed that in every age group cash payment method is mostly used.

-- 9. Which customer segments (based on age, gender, and payment method) generate the most revenue?

SELECT 
    age_group, ROUND(SUM(price), 2) AS revenue
FROM
    sales_data
        NATURAL JOIN
    customer_data
GROUP BY age_group
ORDER BY revenue DESC;

-- seniors i.e, age > 49 generates more revenue from age group segment.

SELECT 
    gender, ROUND(SUM(price), 2) AS revenue
FROM
    sales_data
        NATURAL JOIN
    customer_data
GROUP BY gender
ORDER BY revenue DESC;

-- Females gnerates more revenue from gender segment.

SELECT 
    payment_method, ROUND(SUM(price), 2) AS revenue
FROM
    sales_data
        NATURAL JOIN
    customer_data
GROUP BY payment_method
ORDER BY revenue DESC;

-- cash payment method generates more revenue from payment method segment.

-- 10. What is the average spending per invoice for each age group?

SELECT 
    age_group, ROUND(AVG(price), 2) AS avg_spending
FROM
    sales_data
        NATURAL JOIN
    customer_data
GROUP BY age_group;

-- 11. What is the average quantity of products sold per invoice for each product category?

SELECT 
    category, ROUND(AVG(quantity), 2) AS avg_quantity
FROM
    sales_data
GROUP BY category
ORDER BY avg_quantity;


-- ``````````````````````` Performance of different shopping malla ```````````````````````````
-- 12. How does the performance of different shopping malls compare in terms of sales, customer demographics, and product preferences?

-- in terms of sales

SELECT 
    shopping_mall, SUM(quantity) AS quantity
FROM
    sales_data
GROUP BY shopping_mall
ORDER BY quantity DESC;

-- in terms of age group

with A as
(select shopping_mall, age_group, round(sum(price),2) as revenue
from sales_data
natural join customer_data
group by shopping_mall, age_group
)
select *,
rank() over(partition by shopping_mall order by revenue desc) as rank_
from A;

-- in terms of product preference

with B as
(with A as
(select shopping_mall, category, round(sum(price),2) as revenue
from sales_data
group by shopping_mall, category
)
select *,
rank() over(partition by shopping_mall order by revenue desc) as rank_
from A
)
select *
from B
where rank_ <3;
